### ISSUE TITLE
'UILayoutPriorityDefaultLow' has been renamed to 'UILayoutPriority.defaultLow'

### ISSUE THREAD

**Issue by haroldogtf** [atecle/ATCircularProgressView#2]
In Swift 4.
After pod install, appear this error: 
'UILayoutPriorityDefaultLow' has been renamed to 'UILayoutPriority.defaultLow'

CircularProgressView.swift
> configureImageView()
> height.priority = UILayoutPriorityDefaultLow

**Comment by atecle** [comment]
Thanks @haroldogtf. I'll update this pod for Swift 4

**Comment by atecle** [comment]
Release 1.0.2 supports Swift 4
